spring.application.name=JPQLTutorial-1

# Specify the port for the Spring Boot application (and H2 console)
server.port=8082

# H2 database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL in the logs
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create